from __future__ import annotations

from pathlib import Path
from typing import Protocol


class PlatformAdapter(Protocol):
    def discover_processes(self) -> list[dict[str, object]]: ...
    def register_context_menu(self, actions: list[dict[str, str]]) -> None: ...
    def show_tray_notification(self, notification: dict[str, object]) -> None: ...
    def install_startup_entry(self, command: str) -> None: ...
    def known_install_paths(self, service: str) -> list[Path]: ...
    def open_in_default_app(self, path: Path) -> None: ...

